/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jdbc.program;

import jdbc.model.Mahasiswa;
import jdbc.service.MysqlMahasiswaService;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author qwty
 */
public class jJameUtama extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jJameUtama.class.getName());

    private MysqlMahasiswaService service;
    private DefaultListModel<String> modelID;
    private DefaultListModel<String> modelNama;
    
    /**
     * Creates new form jJameUtama
     */
    public jJameUtama() {
        initComponents();
        service = new MysqlMahasiswaService();
        modelID   = new DefaultListModel<>();
        modelNama = new DefaultListModel<>();
        jListID.setModel(modelID);
        jListNama.setModel(modelNama);
    }

        
    private void refreshList() {
        modelID.clear();
        modelNama.clear();
        List<Mahasiswa> list = service.getAll();
        for (Mahasiswa m : list) {
            modelID.addElement(String.valueOf(m.getId()));
            modelNama.addElement(m.getNama());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListID = new javax.swing.JList<>();
        jLabelID = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListNama = new javax.swing.JList<>();
        jLabelNama = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonGetAll = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNama = new javax.swing.JTextField();
        jButtonAddNama = new javax.swing.JButton();
        jTextFieldIDEdit = new javax.swing.JTextField();
        jTextFieldIDHapus = new javax.swing.JTextField();
        jTextFieldNamaEdit = new javax.swing.JTextField();
        jTextFieldNamaHapus = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jListID.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListID.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListIDValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListID);

        jLabelID.setText("ID");

        jListNama.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListNama.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListNamaValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListNama);

        jLabelNama.setText("Nama");

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel3.setText("KELOLA DATA MAHASISWA ");

        jButtonGetAll.setText("Ambil Semua Data");
        jButtonGetAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGetAllActionPerformed(evt);
            }
        });

        jLabel4.setText("Nama");

        jButtonAddNama.setText("Tambahkan");
        jButtonAddNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddNamaActionPerformed(evt);
            }
        });

        jTextFieldNamaEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamaEditActionPerformed(evt);
            }
        });

        jButton3.setText("Reset Indeks");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonHapus.setText("Hapus");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNama)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldNama)
                                    .addComponent(jButtonAddNama)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldIDEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldNamaEdit))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldIDHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldNamaHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jButtonGetAll, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel3)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonGetAll)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAddNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIDEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNamaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEdit))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldNamaHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonHapus))
                            .addComponent(jTextFieldIDHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelID)
                            .addComponent(jLabelNama))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNamaEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaEditActionPerformed

    private void jButtonGetAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGetAllActionPerformed
        if (service.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Tabel mahasiswa kosong!");
        } else {
            refreshList();
        }
    }//GEN-LAST:event_jButtonGetAllActionPerformed

    private void jButtonAddNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddNamaActionPerformed
        String nama = jTextFieldNama.getText().trim();
        if (nama.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong!");
            return;
        }
        Mahasiswa mhs = service.makeMhsObject();
        mhs.setNama(nama);
        service.add(mhs);
        refreshList();
        jTextFieldNama.setText("");
    }//GEN-LAST:event_jButtonAddNamaActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        String idStr = jTextFieldIDEdit.getText().trim();
        String nama  = jTextFieldNamaEdit.getText().trim();
        
        if (idStr.isEmpty() || nama.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "ID dan Nama harus diisi!");
            return;
        }
        try {
            int id = Integer.parseInt(idStr);
            Mahasiswa cek = service.getById(id);
            if (cek == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "ID " + id + " tidak ditemukan!");
                return;
            }
            Mahasiswa mhs = new Mahasiswa(id, nama);
            service.update(mhs);
            refreshList();
            jTextFieldIDEdit.setText("");
            jTextFieldNamaEdit.setText("");
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "ID harus berupa angka!");
        }
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        String idStr = jTextFieldIDHapus.getText().trim();
        
        if (idStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "ID harus diisi!");
            return;
        }
        try {
            int id = Integer.parseInt(idStr);
            Mahasiswa cek = service.getById(id);
            if (cek == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "ID " + id + " tidak ditemukan!");
                return;
            }
            service.delete(id);
            refreshList();
            jTextFieldIDHapus.setText("");
            jTextFieldNamaHapus.setText("");
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "ID harus berupa angka!");
        }
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Yakin ingin reset indeks? Semua data akan dihapus!",
            "Konfirmasi Reset",
            javax.swing.JOptionPane.YES_NO_OPTION
        );
        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            service.indexReset();
            modelID.clear();
            modelNama.clear();
            javax.swing.JOptionPane.showMessageDialog(this, "Index di reset ke 1");
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jListIDValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListIDValueChanged
        if (!evt.getValueIsAdjusting()) {
            int idx = jListID.getSelectedIndex();
            if (idx >= 0) {
                String id   = modelID.getElementAt(idx);
                String nama = modelNama.getElementAt(idx);
                jTextFieldIDEdit.setText(id);
                jTextFieldNamaEdit.setText(nama);
                jTextFieldIDHapus.setText(id);
                jTextFieldNamaHapus.setText(nama);
            }
        }
    }//GEN-LAST:event_jListIDValueChanged

    private void jListNamaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListNamaValueChanged
        if (!evt.getValueIsAdjusting()) {
            int idx = jListNama.getSelectedIndex();
            if (idx >= 0) {
                String id   = modelID.getElementAt(idx);
                String nama = modelNama.getElementAt(idx);
                jTextFieldIDEdit.setText(id);
                jTextFieldNamaEdit.setText(nama);
                jTextFieldIDHapus.setText(id);
                jTextFieldNamaHapus.setText(nama);
            }
        }
    }//GEN-LAST:event_jListNamaValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jJameUtama().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAddNama;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonGetAll;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JList<String> jListID;
    private javax.swing.JList<String> jListNama;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldIDEdit;
    private javax.swing.JTextField jTextFieldIDHapus;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldNamaEdit;
    private javax.swing.JTextField jTextFieldNamaHapus;
    // End of variables declaration//GEN-END:variables
}
